### ISSUE TITLE
traceback when trying trytls on fedora 24

### ISSUE THREAD

**Issue by ikisusi** [ouspg/trytls#129]
```
$ cat /etc/redhat-release 
Fedora release 24 (Twenty Four)

$ python -V
Python 2.7.11

$ pip install --user trytls
Collecting trytls
  Using cached trytls-0.1.1-py2.py3-none-any.whl
Collecting colorama (from trytls)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Installing collected packages: colorama, trytls
Successfully installed colorama trytls
You are using pip version 8.0.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ ~/.local/bin/trytls 
Traceback (most recent call last):
  File "/home/fenris/.local/bin/trytls", line 11, in <module>
    sys.exit(main())
  File "/home/fenris/.local/lib/python2.7/site-packages/trytls/runner.py", line 236, in main
    bundles = sorted(iter_bundles())
  File "/home/fenris/.local/lib/python2.7/site-packages/trytls/runner.py", line 196, in iter_bundles
    for entry in pkg_resources.iter_entry_points("trytls.bundles"):
AttributeError: 'module' object has no attribute 'iter_entry_points'
```

**Comment by ikisusi** [comment]
Closing this as invalid, problem was with broken permission on the target machine. Setuptools directory in global site-packages had unreadable files that broke the software. Machine's operating system install was fixed and the problem went away. Thank @jviide for help!
