### ISSUE TITLE
Debian 7 issue with python2-urllib2

### ISSUE THREAD

**Issue by evilon** [ouspg/trytls#212]
Debian 7 has  Python 2.7.3

```
# trytls https python python2-urllib2/run.py
platform: Linux
runner: trytls 0.3.0 (CPython 3.5.2, OpenSSL 1.0.1e)
stub: python python2-urllib2/run.py
ERROR valid certificate Common Name [accept domain-match.badtls.io:10000]
      reason: stub exited with return code 1
      output: Traceback (most recent call last):
                File "python2-urllib2/run.py", line 14, in <module>
                  except ssl.CertificateError:
              AttributeError: 'module' object has no attribute 'CertificateError'
ERROR valid wildcard certificate Common Name [accept wildcard-match.badtls.io:10001]
      reason: stub exited with return code 1
      output: Traceback (most recent call last):
                File "python2-urllib2/run.py", line 14, in <module>
                  except ssl.CertificateError:
              AttributeError: 'module' object has no attribute 'CertificateError'
ERROR support for Subject Alternative Name (SAN) [accept san-match.badtls.io:10002]
      reason: stub exited with return code 1
      output: Traceback (most recent call last):
                File "python2-urllib2/run.py", line 14, in <module>
                  except ssl.CertificateError:
              AttributeError: 'module' object has no attribute 'CertificateError'
```

**Comment by Mamietti** [comment]
Not likely an issue.
