### ISSUE TITLE
TryTLS missing depencies on CentOS 6

### ISSUE THREAD

**Issue by oherrala** [ouspg/trytls#29]
This is with Python 2.6 on CentOS 6:

```
$ cat /etc/centos-release 
CentOS release 6.8 (Final)
$ python -V
Python 2.6.6
```

```
Traceback (most recent call last):
  File "/usr/bin/trytls", line 9, in <module>
    load_entry_point('trytls==0.0.3', 'console_scripts', 'trytls')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/showrunner/runner.py", line 3, in <module>
    import argparse
ImportError: No module named argparse
```

Is this something which could be in `requirements.txt`?

**Comment by oherrala** [comment]
Installing `python-argparse` on CentOS 6 fixes this issue, but the question about `requirements.txt` still stands.

**Comment by oherrala** [comment]
Same thing for `importlib`:

```
Traceback (most recent call last):
  File "/usr/bin/trytls", line 9, in <module>
    load_entry_point('trytls==0.0.3', 'console_scripts', 'trytls')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/showrunner/runner.py", line 4, in <module>
    import importlib
ImportError: No module named importlib
```

Installing `python-importlib` on CentOS 6 fixes this.

**Comment by jviide** [comment]
Let's just stick to Python 2.7.9 and newer for the time being. PR #33 adds related checks to `setup.py`.

**Comment by oherrala** [comment]
To run TryTLS on CentOS 6 install Python from [IUS](https://ius.io/):

```
# cat /etc/redhat-release 
CentOS release 6.8 (Final)
# yum install https://centos6.iuscommunity.org/ius-release.rpm
# yum install python27 python27-pip
# python2.7 -V
Python 2.7.11
# pip2.7 install git+git://github.com/ouspg/trytls.git  # This requires `git` to be in path
```

And then just `trytls`.
