### ISSUE TITLE
aiohttp stub prints tracebacks for caught exceptions

### ISSUE THREAD

**Issue by oherrala** [ouspg/trytls#302]
For example:

```console
$ python3 run.py wrong.host.badssl.com 443
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 503, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 688, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 321, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'wrong.host.badssl.com' doesn't match either of '*.badssl.com', 'badssl.com'
REJECT
```

Related issues:
* https://github.com/KeepSafe/aiohttp/issues/1116
* https://github.com/python/asyncio/issues/404
* https://github.com/ouspg/trytls/pull/252

Upstream fix (not verified):
* https://github.com/python/asyncio/pull/460

**Comment by jdbertron** [comment]
Why are these issues all marked resolved when they're not. This is still happening.
