### ISSUE TITLE
OSError: [Errno 2] No such file or directory when OpenSSL is not installed

### ISSUE THREAD

**Issue by oherrala** [ouspg/trytls#32]
This is from CentOS 7 when `openssl` package is not installed:

```
Traceback (most recent call last):
  File "/usr/bin/trytls", line 9, in <module>
    load_entry_point('trytls==0.0.3', 'console_scripts', 'trytls')()
  File "/usr/lib/python2.7/site-packages/showrunner/runner.py", line 122, in main
    run([args.command] + args.args, args.test_bundle)
  File "/usr/lib/python2.7/site-packages/showrunner/runner.py", line 60, in run
    with test() as (ok_expected, host, port, cafile):
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/site-packages/showrunner/testenv.py", line 89, in local
    certdata, keydata, cadata = gencert(cn)
  File "/usr/lib/python2.7/site-packages/showrunner/gencert.py", line 30, in gencert
    ca_key = _ca_key()
  File "/usr/lib/python2.7/site-packages/showrunner/utils.py", line 14, in _memoized
    value.append(func())
  File "/usr/lib/python2.7/site-packages/showrunner/gencert.py", line 20, in _ca_key
    return openssl(["genrsa", "4096"])
  File "/usr/lib/python2.7/site-packages/showrunner/gencert.py", line 10, in openssl
    stderr=subprocess.PIPE
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by Mamietti** [comment]
So...we should add that openssl is a requirement? Do explain a bit further what is the issue here.

**Comment by oherrala** [comment]
Throwing exception to end user is ugly. It's difficult to decipher what happened and how to correct the situation.

Document the requirement of openssl command (it must be installed and it must be in $PATH). Also, is there version requirements?

Also catch the OSError exception (where errno is ENOENT) in [gencert.py:openssl()](https://github.com/ouspg/trytls/blob/7f4e709254588ffd637d717ecc918ac27b3cb5ef/showrunner/gencert.py#L6-11) function and return error message ("Command openssl not found in $PATH") and exit with non-zero return value.

**Comment by ikisusi** [comment]
Hmmm, is $PATH platform agnostics? How about "openssl command not found in the search path" or similar.

**Comment by jviide** [comment]
👍 for the "openssl command not found in the search path". Another option would be to use something like pyOpenSSL for generating certs.
